service: fwi-poker-leaderboard-serverless

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 128
  stage: dev
#  region: us-east-1

package:
  exclude:
    - .gitignore
    - .git/**

functions:
  ping:
    handler: controllers.ping
    events:
     - http:
         path: ping
         method: get

  createPlayer:
    handler: controllers.createPlayer
    events:
      - http:
          path: players
          method: post
          cors: true

  getPlayer:
    handler: controllers.getPlayer
    events:
      - http:
          path: players/{id}
          method: get
          cors: true

  getPlayers:
    handler: controllers.getPlayers
    events:
     - http:
         path: players
         method: get
         cors: true

  updatePlayer:
    handler: controllers/updatePlayer
    events:
     - http:
         path: players/{id}
         method: put
         cors: true

  deletePlayer:
    handler: controllers/deletePlayer
    events:
     - http:
         path: players/{id}
         method: delete
         cors: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    port: 4000
